%find all to all energy needs

%energies to 1

function [energy_to_be_consumedALL,nodes_overhead_energy_consumption_CI_ALL,encryptionhash_energy_ALL]=neo_nodetoallenergies(CItargets,CInodes,energy_info,total_blocks)
target_CI1=CItargets(1,:);
target_CI2=CItargets(2,:);
target_CI3=CItargets(3,:);


node_CI1=CInodes(:,1:2);
node_CI2=CInodes(:,3:4);
node_CI3=CInodes(:,5:6);

%present nodeCI1 to targetCI 123 çiko

[energy_to_be_consumed_nodeCI1_to_targetCI1,nodes_overhead_energy_consumption_nodeCI1_to_targetCI1,...
    C_consumption_nodeCI1_to_targetCI1,C_overhead_nodeCI1_to_targetCI1,I_consumption_nodeCI1_to_targetCI1,I_overhead_nodeCI1_to_targetCI1]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI1,node_CI1, ...
    energy_info, ...
    total_blocks);
 
[energy_to_be_consumed_nodeCI1_to_targetCI2,nodes_overhead_energy_consumption_nodeCI1_to_targetCI2,...
    C_consumption_nodeCI1_to_targetCI2,C_overhead_nodeCI1_to_targetCI2,I_consumption_nodeCI1_to_targetCI2,I_overhead_nodeCI1_to_targetCI2]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI2,node_CI1, ...
    energy_info, ...
    total_blocks);

[energy_to_be_consumed_nodeCI1_to_targetCI3,nodes_overhead_energy_consumption_nodeCI1_to_targetCI3,...
    C_consumption_nodeCI1_to_targetCI3,C_overhead_nodeCI1_to_targetCI3,I_consumption_nodeCI1_to_targetCI3,I_overhead_nodeCI1_to_targetCI3]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI3,node_CI1, ...
    energy_info, ...
    total_blocks);


%present nodeCI2 to targetCI 123

[energy_to_be_consumed_nodeCI2_to_targetCI1,nodes_overhead_energy_consumption_nodeCI2_to_targetCI1,...
    C_consumption_nodeCI2_to_targetCI1,C_overhead_nodeCI2_to_targetCI1,I_consumption_nodeCI2_to_targetCI1,I_overhead_nodeCI2_to_targetCI1]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI1,node_CI2, ...
    energy_info, ...
    total_blocks);

[energy_to_be_consumed_nodeCI2_to_targetCI2,nodes_overhead_energy_consumption_nodeCI2_to_targetCI2,...
    C_consumption_nodeCI2_to_targetCI2,C_overhead_nodeCI2_to_targetCI2,I_consumption_nodeCI2_to_targetCI2,I_overhead_nodeCI2_to_targetCI2]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI2,node_CI2, ...
    energy_info, ...
    total_blocks);

[energy_to_be_consumed_nodeCI2_to_targetCI3,nodes_overhead_energy_consumption_nodeCI2_to_targetCI3,...
    C_consumption_nodeCI2_to_targetCI3,C_overhead_nodeCI2_to_targetCI3,I_consumption_nodeCI2_to_targetCI3,I_overhead_nodeCI2_to_targetCI3]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI3,node_CI2, ...
    energy_info, ...
    total_blocks);

%present nodeCI3 to targetCI 123

[energy_to_be_consumed_nodeCI3_to_targetCI1,nodes_overhead_energy_consumption_nodeCI3_to_targetCI1,...
    C_consumption_nodeCI3_to_targetCI1,C_overhead_nodeCI3_to_targetCI1,I_consumption_nodeCI3_to_targetCI1,I_overhead_nodeCI3_to_targetCI1]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI1,node_CI3, ...
    energy_info, ...
    total_blocks);

[energy_to_be_consumed_nodeCI3_to_targetCI2,nodes_overhead_energy_consumption_nodeCI3_to_targetCI2,...
    C_consumption_nodeCI3_to_targetCI2,C_overhead_nodeCI3_to_targetCI2,I_consumption_nodeCI3_to_targetCI2,I_overhead_nodeCI3_to_targetCI2]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI2,node_CI3, ...
    energy_info, ...
    total_blocks);

[energy_to_be_consumed_nodeCI3_to_targetCI3,nodes_overhead_energy_consumption_nodeCI3_to_targetCI3,...
    C_consumption_nodeCI3_to_targetCI3,C_overhead_nodeCI3_to_targetCI3,I_consumption_nodeCI3_to_targetCI3,I_overhead_nodeCI3_to_targetCI3]= ...         %C_overhead ve I_overhead 100x1 vector
    neo_calc_energy(target_CI3,node_CI3, ...
    energy_info, ...
    total_blocks);



energy_to_be_consumedALL=  [energy_to_be_consumed_nodeCI1_to_targetCI1,...
                            energy_to_be_consumed_nodeCI1_to_targetCI2,...
                            energy_to_be_consumed_nodeCI1_to_targetCI3,...
                            energy_to_be_consumed_nodeCI2_to_targetCI1,...
                            energy_to_be_consumed_nodeCI2_to_targetCI2,...
                            energy_to_be_consumed_nodeCI2_to_targetCI3,...
                            energy_to_be_consumed_nodeCI3_to_targetCI1,...
                            energy_to_be_consumed_nodeCI3_to_targetCI2,...
                            energy_to_be_consumed_nodeCI3_to_targetCI3];


%node to target
nodes_overhead_energy_consumption_CI_ALL=  [nodes_overhead_energy_consumption_nodeCI1_to_targetCI1,...
	                                        nodes_overhead_energy_consumption_nodeCI1_to_targetCI2,...
	                                        nodes_overhead_energy_consumption_nodeCI1_to_targetCI3,...
	                                        nodes_overhead_energy_consumption_nodeCI2_to_targetCI1,...
	                                        nodes_overhead_energy_consumption_nodeCI2_to_targetCI2,...
	                                        nodes_overhead_energy_consumption_nodeCI2_to_targetCI3,...
	                                        nodes_overhead_energy_consumption_nodeCI3_to_targetCI1,...
	                                        nodes_overhead_energy_consumption_nodeCI3_to_targetCI2,...
	                                        nodes_overhead_energy_consumption_nodeCI3_to_targetCI3];


encryptionhash_energy_ALL=energy_to_be_consumedALL-nodes_overhead_energy_consumption_CI_ALL;

end