
%fonksiyon sirali gider 1 2 3 diye yazildiysa once 1den sonra 3ten 
% sonra 2den kontrol eder
%neo_InitialActiveNodes

function [used_node_specs1,used_node_specs2,used_node_specs3,...
            ActiveNodesAtStart,initcoverages]=neo_InitialActiveNodes( ozellikleri_saglayan_nodelarin_spec1to1,...
                                    ozellikleri_saglayan_nodelarin_spec3to1,...
                                    ozellikleri_saglayan_nodelarin_spec2to1,...
                                    ozellikleri_saglayan_nodelarin_spec2to2,...
                                    ozellikleri_saglayan_nodelarin_spec3to2,...
                                    ozellikleri_saglayan_nodelarin_spec1to2,...
                                    ozellikleri_saglayan_nodelarin_spec3to3,...
                                    ozellikleri_saglayan_nodelarin_spec2to3,...
                                    ozellikleri_saglayan_nodelarin_spec1to3,...
                                    ALLNODES,grno_a,grno_b,grno_c)
node_number=size(ALLNODES,1);
[  used_node_specs1,...
            placedALLNODESto1]...
            = neo_ilkusednodes( ozellikleri_saglayan_nodelarin_spec1to1,grno_a,...
                                ozellikleri_saglayan_nodelarin_spec2to1,grno_b,...
                                ozellikleri_saglayan_nodelarin_spec3to1,grno_c,...
                                ALLNODES);


[           used_node_specs2,...
            placedALLNODESto2]...
            = neo_ilkusednodes( ozellikleri_saglayan_nodelarin_spec2to2,grno_b,...
                                ozellikleri_saglayan_nodelarin_spec1to2,grno_a,...
                                ozellikleri_saglayan_nodelarin_spec3to2,grno_c,...
                                placedALLNODESto1);

[           used_node_specs3,...
            placedALLNODESto3]...
            = neo_ilkusednodes( ozellikleri_saglayan_nodelarin_spec3to3,grno_c,...
                                ozellikleri_saglayan_nodelarin_spec1to3,grno_a,...
                                ozellikleri_saglayan_nodelarin_spec2to3,grno_b,...
                                placedALLNODESto2);

%yerlestikleri grubu yazıyorum

ActiveNodesAtStart=placedALLNODESto3;


allactives=[ActiveNodesAtStart(:,6) ; ActiveNodesAtStart(:,12) ; ActiveNodesAtStart(:,18)];

% %active node sayısı ve coverage bulma
NO_passives=sum(allactives==0); 
NO_actives1=sum(allactives==grno_a); icov1=NO_actives1/node_number;
NO_actives2=sum(allactives==grno_b); icov2=NO_actives2/node_number;
NO_actives3=sum(allactives==grno_c); icov3=NO_actives3/node_number;
initcoverages=[icov1,icov2,icov3];

% disp('actives placed');

%bir ovehead energy hepsi için aynı degil bunu eskiden oyle hesaplamistik
% ovENERGY=abs(nodes_overhead_energy_consumption_CI1to1-nodes_overhead_energy_consumption_CI2to1);    %bu aslında tek değer

%enerji tüketilmiş halini bulur  BUNU BULMAK ICIN TUM YERLESTIRMELERE GORE
%HANGI TUKETIM DEGERINI CEKECEGINE BAKMAK LAZIM 

% [new_node_alltoall]= newALLNODES(target_CI1,target_CI2,target_CI3,ALLNODES,used_node_specs1,used_node_specs2,used_node_specs3,ovENERGY,placedALLNODES_AlltoAll);
% ActiveNodesAtStart;
% ActiveNodesAfterConsume=new_node_alltoall;





% diffelements=sum(ALLNODES~=new_node_all)
% 
% initcoverages;