
function [ALLplacednodes_w_passives,coverageafterpassives,...
    used_passive_node_specs1,used_passive_node_specs2,used_passive_node_specs3]=...
    neo_CheckPassiveNodesfunc(ozellikleri_saglayabilecek_node_IDs1to1,...   %ilk kontrol
                        ozellikleri_saglayabilecek_node_IDs2to1,...          %son kontrol
                        ozellikleri_saglayabilecek_node_IDs3to1,...          %ikincikontrol
                        ozellikleri_saglayabilecek_node_IDs1to2,...   %ilk kontrol
                        ozellikleri_saglayabilecek_node_IDs2to2,...          %son kontrol.
                        ozellikleri_saglayabilecek_node_IDs3to2,...
                        ozellikleri_saglayabilecek_node_IDs1to3,...   %ilk kontrol
                        ozellikleri_saglayabilecek_node_IDs2to3,...          %son kontrol
                        ozellikleri_saglayabilecek_node_IDs3to3,...
                        ActiveNodesAtStart,grno_a,grno_b,grno_c,av1,av2,av3)

node_number=size(ActiveNodesAtStart,1);

 [  used_passive_node_IDs1,...
            used_passive_node_GRs1,...
            used_passive_node_specs1,...
            ~,...
            ~,...
            placedpassiveNODESto1,initcov1p,optcov1p]...
            = neo_UsedPassiveNodes(ozellikleri_saglayabilecek_node_IDs1to1,grno_a,...   %ilk kontrol
                        ozellikleri_saglayabilecek_node_IDs2to1,grno_b,...          %son kontrol
                        ozellikleri_saglayabilecek_node_IDs3to1,grno_c,...          %ikincikontrol
                        ActiveNodesAtStart,av1,av2,av3);

 %newnodesspec
%ilk yerlestirmeden sonra place guncelleme

 ActiveNodes_w_passive1=placedpassiveNODESto1;

 [  used_passive_node_IDs2,...
            used_passive_node_GRs2,...
            used_passive_node_specs2,...
             ~,...
             ~,...
            placedpassiveNODESto2,initcov2p,optcov2p]...
            = neo_UsedPassiveNodes(ozellikleri_saglayabilecek_node_IDs2to2,grno_b,...   %ilk kontrol
                        ozellikleri_saglayabilecek_node_IDs1to2,grno_a,...          %son kontrol
                        ozellikleri_saglayabilecek_node_IDs3to2,grno_c,...          %ikincikontrol
                        ActiveNodes_w_passive1,av2,av1,av3);

%ikinci yerlestirmeden sonra place atama
 ActiveNodes_w_passive2=placedpassiveNODESto2;

%ucuncu gruba diger grupların passivelerden secip atama
[  used_passive_node_IDs3,...
            used_passive_node_GRs3,...
            used_passive_node_specs3,...
             ~,...
             ~,...
            placedpassiveNODESto3,initcov3p,optcov3p]...
            = neo_UsedPassiveNodes(ozellikleri_saglayabilecek_node_IDs3to3,grno_c,...   %ilk kontrol
                        ozellikleri_saglayabilecek_node_IDs1to3,grno_a,...          %son kontrol
                        ozellikleri_saglayabilecek_node_IDs2to3,grno_b,...          %ikincikontrol
                        ActiveNodes_w_passive2,av3,av1,av2);

%ucuncu yerlestirmeden sonra place atama
 ALLplacednodes_w_passives=placedpassiveNODESto3;

coverageafterpassive1= calculatecoverage_no_consumtpion(ALLplacednodes_w_passives,grno_a,node_number);
coverageafterpassive2= calculatecoverage_no_consumtpion(ALLplacednodes_w_passives,grno_b,node_number);
coverageafterpassive3= calculatecoverage_no_consumtpion(ALLplacednodes_w_passives,grno_c,node_number);



initcoverages=[initcov1p,initcov2p,initcov3p];
coverageafterpassives=[coverageafterpassive1,coverageafterpassive2,coverageafterpassive3];
end