%find all groups to all targets

%target one to all
%compares target 1 and first matrix
[ozellikleri_saglayan_nodelarin_spec1to1,...
    ozellikleri_saglayan_node_IDs1to1, ...
    ozellikleri_saglayabilecek_nodelarin_spec1to1,...
    ozellikleri_saglayabilecek_node_IDs1to1,...
    ozellikleri_saglayamayan_nodelarin_spec1to1,...
    ozellikleri_saglayamayan_node_IDs1to1,...
    allpossible_node_IDs1to1,...
    allpossible_node_specs1to1...
    ]= neo_find_nodes(node_group1p,target_CI1,energy_to_be_consumed1to1,encryption_energy_1to1);

%compares target1 and the second matrix
[ozellikleri_saglayan_nodelarin_spec2to1,...
    ozellikleri_saglayan_node_IDs2to1, ...
    ozellikleri_saglayabilecek_nodelarin_spec2to1,...
    ozellikleri_saglayabilecek_node_IDs2to1,...
    ozellikleri_saglayamayan_nodelarin_spec2to1,...
    ozellikleri_saglayamayan_node_IDs2to1,...
    allpossible_node_IDs2to1,...
    allpossible_node_specs2to1...
    ]= neo_find_nodes(node_group2p,target_CI1,energy_to_be_consumed2to1,encryption_energy_2to1);

%compares target and the third matrix
[ozellikleri_saglayan_nodelarin_spec3to1,...
    ozellikleri_saglayan_node_IDs3to1, ...
    ozellikleri_saglayabilecek_nodelarin_spec3to1,...
    ozellikleri_saglayabilecek_node_IDs3to1,...
    ozellikleri_saglayamayan_nodelarin_spec3to1,...
    ozellikleri_saglayamayan_node_IDs3to1,...
    allpossible_node_IDs3to1,...
    allpossible_node_specs3to1...
    ]= neo_find_nodes(node_group3p,target_CI1,energy_to_be_consumed3to1,encryption_energy_3to1);

%%%%%%%%%%%%%%%%%%%%
%compares target 2 and all
%%%%%%%%%%%%%%%%%%%%

%compares target and the first matrix
[ozellikleri_saglayan_nodelarin_spec1to2,...
    ozellikleri_saglayan_node_IDs1to2, ...
    ozellikleri_saglayabilecek_nodelarin_spec1to2,...
    ozellikleri_saglayabilecek_node_IDs1to2,...
    ozellikleri_saglayamayan_nodelarin_spec1to2,...
    ozellikleri_saglayamayan_node_IDs1to2,...
    allpossible_node_IDs1to2,...
    allpossible_node_specs1to2...
    ]= neo_find_nodes(node_group1p,target_CI2,energy_to_be_consumed1to2,encryption_energy_1to2);

%compares target and the second matrix
[ozellikleri_saglayan_nodelarin_spec2to2,...
    ozellikleri_saglayan_node_IDs2to2, ...
    ozellikleri_saglayabilecek_nodelarin_spec2to2,...
    ozellikleri_saglayabilecek_node_IDs2to2,...
    ozellikleri_saglayamayan_nodelarin_spec2to2,...
    ozellikleri_saglayamayan_node_IDs2to2,...
    allpossible_node_IDs2to2,...
    allpossible_node_specs2to2...
    ]= neo_find_nodes(node_group2p,target_CI2,energy_to_be_consumed2to2,encryption_energy_2to2);

%compares target and the third matrix
[ozellikleri_saglayan_nodelarin_spec3to2,...
    ozellikleri_saglayan_node_IDs3to2, ...
    ozellikleri_saglayabilecek_nodelarin_spec3to2,...
    ozellikleri_saglayabilecek_node_IDs3to2,...
    ozellikleri_saglayamayan_nodelarin_spec3to2,...
    ozellikleri_saglayamayan_node_IDs3to2,...
    allpossible_node_IDs3to2,...
    allpossible_node_specs3to2...
    ]= neo_find_nodes(node_group3p,target_CI2,energy_to_be_consumed3to2,encryption_energy_3to2);



%%%%%%%%%%%%%%%%%%%%%%%%%
%compares target 3 and all
%%%%%%%%%%%%%%%%%%%%%%%%%

%compares target and the first matrix
[ozellikleri_saglayan_nodelarin_spec1to3,...
    ozellikleri_saglayan_node_IDs1to3, ...
    ozellikleri_saglayabilecek_nodelarin_spec1to3,...
    ozellikleri_saglayabilecek_node_IDs1to3,...
    ozellikleri_saglayamayan_nodelarin_spec1to3,...
    ozellikleri_saglayamayan_node_IDs1to3,...
    allpossible_node_IDs1to3,...
    allpossible_node_specs1to3...
    ]= neo_find_nodes(node_group1p,target_CI3,energy_to_be_consumed1to3,encryption_energy_1to3);

%compares target and the second group
[ozellikleri_saglayan_nodelarin_spec2to3,...
    ozellikleri_saglayan_node_IDs2to3, ...
    ozellikleri_saglayabilecek_nodelarin_spec2to3,...
    ozellikleri_saglayabilecek_node_IDs2to3,...
    ozellikleri_saglayamayan_nodelarin_spec2to3,...
    ozellikleri_saglayamayan_node_IDs2to3,...
    allpossible_node_IDs2to3,...
    allpossible_node_specs2to3...
    ]= neo_find_nodes(node_group2p,target_CI3,energy_to_be_consumed2to3,encryption_energy_2to3);

%compares target and the third group
[ozellikleri_saglayan_nodelarin_spec3to3,...
    ozellikleri_saglayan_node_IDs3to3, ...
    ozellikleri_saglayabilecek_nodelarin_spec3to3,...
    ozellikleri_saglayabilecek_node_IDs3to3,...
    ozellikleri_saglayamayan_nodelarin_spec3to3,...
    ozellikleri_saglayamayan_node_IDs3to3,...
    allpossible_node_IDs3to3,...
    allpossible_node_specs3to3...
    ]= neo_find_nodes(node_group3p,target_CI3,energy_to_be_consumed3to3,encryption_energy_3to3);








% %find all groups to all targets
% 
% %target one to all
% %compares target 1 and first matrix
% [ozellikleri_saglayan_nodelarin_spec1to1,...
%     ozellikleri_saglayan_node_IDs1to1, ...
%     ozellikleri_saglayabilecek_nodelarin_spec1to1,...
%     ozellikleri_saglayabilecek_node_IDs1to1,...
%     ozellikleri_saglayamayan_nodelarin_spec1to1,...
%     ozellikleri_saglayamayan_node_IDs1to1,...
%     allpossible_node_IDs1to1,...
%     allpossible_node_specs1to1...
%     ]= neo_find_nodes(node_group1p,target_CI1,energy_to_be_consumed1to1,encryption_energy_1to1);
% 
% %compares target1 and the second matrix
% [ozellikleri_saglayan_nodelarin_spec2to1,...
%     ozellikleri_saglayan_node_IDs2to1, ...
%     ozellikleri_saglayabilecek_nodelarin_spec2to1,...
%     ozellikleri_saglayabilecek_node_IDs2to1,...
%     ozellikleri_saglayamayan_nodelarin_spec2to1,...
%     ozellikleri_saglayamayan_node_IDs2to1,...
%     allpossible_node_IDs2to1,...
%     allpossible_node_specs2to1...
%     ]= neo_find_nodes(node_group2p,target_CI1,energy_to_be_consumed2to1,encryption_energy_2to1);
% 
% %compares target and the third matrix
% [ozellikleri_saglayan_nodelarin_spec3to1,...
%     ozellikleri_saglayan_node_IDs3to1, ...
%     ozellikleri_saglayabilecek_nodelarin_spec3to1,...
%     ozellikleri_saglayabilecek_node_IDs3to1,...
%     ozellikleri_saglayamayan_nodelarin_spec3to1,...
%     ozellikleri_saglayamayan_node_IDs3to1,...
%     allpossible_node_IDs3to1,...
%     allpossible_node_specs3to1...
%     ]= neo_find_nodes(node_group3p,target_CI1,energy_to_be_consumed3to1,encryption_energy_3to1);
% 
% %%%%%%%%%%%%%%%%%%%%
% %compares target 2 and all
% %%%%%%%%%%%%%%%%%%%%
% 
% %compares target and the first matrix
% [ozellikleri_saglayan_nodelarin_spec1to2,...
%     ozellikleri_saglayan_node_IDs1to2, ...
%     ozellikleri_saglayabilecek_nodelarin_spec1to2,...
%     ozellikleri_saglayabilecek_node_IDs1to2,...
%     ozellikleri_saglayamayan_nodelarin_spec1to2,...
%     ozellikleri_saglayamayan_node_IDs1to2,...
%     allpossible_node_IDs1to2,...
%     allpossible_node_specs1to2...
%     ]= neo_find_nodes(node_group1p,target_CI2,energy_to_be_consumed1to2,encryption_energy_1to2);
% 
% %compares target and the second matrix
% [ozellikleri_saglayan_nodelarin_spec2to2,...
%     ozellikleri_saglayan_node_IDs2to2, ...
%     ozellikleri_saglayabilecek_nodelarin_spec2to2,...
%     ozellikleri_saglayabilecek_node_IDs2to2,...
%     ozellikleri_saglayamayan_nodelarin_spec2to2,...
%     ozellikleri_saglayamayan_node_IDs2to2,...
%     allpossible_node_IDs2to2,...
%     allpossible_node_specs2to2...
%     ]= neo_find_nodes(node_group2p,target_CI2,energy_to_be_consumed2to2,encryption_energy_2to2);
% 
% %compares target and the third matrix
% [ozellikleri_saglayan_nodelarin_spec3to2,...
%     ozellikleri_saglayan_node_IDs3to2, ...
%     ozellikleri_saglayabilecek_nodelarin_spec3to2,...
%     ozellikleri_saglayabilecek_node_IDs3to2,...
%     ozellikleri_saglayamayan_nodelarin_spec3to2,...
%     ozellikleri_saglayamayan_node_IDs3to2,...
%     allpossible_node_IDs3to2,...
%     allpossible_node_specs3to2...
%     ]= neo_find_nodes(node_group3p,target_CI2,energy_to_be_consumed3to2,encryption_energy_3to2);
% 
% 
% 
% %%%%%%%%%%%%%%%%%%%%%%%%%
% %compares target 3 and all
% %%%%%%%%%%%%%%%%%%%%%%%%%
% 
% %compares target and the first matrix
% [ozellikleri_saglayan_nodelarin_spec1to3,...
%     ozellikleri_saglayan_node_IDs1to3, ...
%     ozellikleri_saglayabilecek_nodelarin_spec1to3,...
%     ozellikleri_saglayabilecek_node_IDs1to3,...
%     ozellikleri_saglayamayan_nodelarin_spec1to3,...
%     ozellikleri_saglayamayan_node_IDs1to3,...
%     allpossible_node_IDs1to3,...
%     allpossible_node_specs1to3...
%     ]= neo_find_nodes(node_group1p,target_CI3,energy_to_be_consumed1to3,encryption_energy_1to3);
% 
% %compares target and the second group
% [ozellikleri_saglayan_nodelarin_spec2to3,...
%     ozellikleri_saglayan_node_IDs2to3, ...
%     ozellikleri_saglayabilecek_nodelarin_spec2to3,...
%     ozellikleri_saglayabilecek_node_IDs2to3,...
%     ozellikleri_saglayamayan_nodelarin_spec2to3,...
%     ozellikleri_saglayamayan_node_IDs2to3,...
%     allpossible_node_IDs2to3,...
%     allpossible_node_specs2to3...
%     ]= neo_find_nodes(node_group2p,target_CI3,energy_to_be_consumed2to3,encryption_energy_2to3);
% 
% %compares target and the third group
% [ozellikleri_saglayan_nodelarin_spec3to3,...
%     ozellikleri_saglayan_node_IDs3to3, ...
%     ozellikleri_saglayabilecek_nodelarin_spec3to3,...
%     ozellikleri_saglayabilecek_node_IDs3to3,...
%     ozellikleri_saglayamayan_nodelarin_spec3to3,...
%     ozellikleri_saglayamayan_node_IDs3to3,...
%     allpossible_node_IDs3to3,...
%     allpossible_node_specs3to3...
%     ]= neo_find_nodes(node_group3p,target_CI3,energy_to_be_consumed3to3,encryption_energy_3to3);
% 
% 
% 
% 
% 
