
%tektek
clear
%clc
sim_INPUTS;

[grno_a,grno_b,grno_c,generate_CI1,generate_CI2,generate_CI3,...
    node_group1,node_group2,node_group3,target_CIA_in_av_order]=...
    neoGenerateNodesFunction(node_number,israndom,budget,potentialimpact_n1,potentialimpact_n2,potentialimpact_n3);     %test icin icerde deger ver


%create ALLNODES for decision input
placezero=zeros(node_number,1);
ALLNODES=[node_group1,placezero,node_group2,placezero,node_group3,placezero];
NodesAtStart=ALLNODES;
changedmatrix2=ALLNODES;

boy=size(1:M:B ,2);
init_cov_mat=zeros(boy,3);
passive_cov_mat=zeros(boy,3);
outp_cov_mat=zeros(boy,3);

row_ind=1;
%FOR LOOP BURAYA GELECEK
for i=1:M:time
    ALLNODES=changedmatrix2;
    places=[6, 12, 18];
    ALLNODES(:,places)=0;
        node_group1p=ALLNODES(:,1:5);
        node_group2p=ALLNODES(:,7:11);
        node_group3p=ALLNODES(:,13:17);
    
    [av1,av2,av3,target_CI1,target_CI2,target_CI3,...
        node_CI1, node_CI2,node_CI3 ,energy_to_be_consumedALL,...
        nodes_overhead_energy_consumption_CI_ALL,encryption_energy_ALL,OverheadMatrix128192256]=...
        neoCalculateNeededEnergiesFunction(total_blocks,target_CIA_in_av_order,...
                                            generate_CI1,generate_CI2,generate_CI3,...
                                            node_group1p,node_group2p,node_group3p);
    energyisimleriatama
    
    %ALLNODES
    % tic
    neo_findallpossiblenodes   %%findallpossiblenodes1 dersen sadece 1incileri bulur
    % disp('find node complete');
    
    [used_node_specs1,used_node_specs2,used_node_specs3,...
                ActiveNodesAtStart,initcoverages]=...
                neo_InitialActiveNodes( ozellikleri_saglayan_nodelarin_spec1to1,...
                                        ozellikleri_saglayan_nodelarin_spec3to1,...
                                        ozellikleri_saglayan_nodelarin_spec2to1,...
                                        ozellikleri_saglayan_nodelarin_spec2to2,...
                                        ozellikleri_saglayan_nodelarin_spec3to2,...
                                        ozellikleri_saglayan_nodelarin_spec1to2,...
                                        ozellikleri_saglayan_nodelarin_spec3to3,...
                                        ozellikleri_saglayan_nodelarin_spec2to3,...
                                        ozellikleri_saglayan_nodelarin_spec1to3,...
                                        ALLNODES,grno_a,grno_b,grno_c);
    %ActiveNodesAtStart   %ilk yerlestirmeler sadece her grupta yer alan active nodeları buluyor
    %bunu optimizasyon adımı olarak kullanmadim optimizasyon oncesini gormek
    %icin kullandim ve calistirdim  matrisi optimizasyonsuz degerleri verir
    % initcoverages;
    
    if (initcoverages(1) < av1 || initcoverages(2) < av2 || initcoverages(3) < av3) 
       
        
        [Allplaced_afteropt,coverageafteropt,...                      %ALLplacednodes_w_passives ,coverage after passive
            used_passive_node_specs1,used_passive_node_specs2,used_passive_node_specs3]=...
            neo_CheckPassiveNodesfunc(ozellikleri_saglayabilecek_node_IDs1to1,...   %ilk kontrol
                                ozellikleri_saglayabilecek_node_IDs2to1,...          %son kontrol
                                ozellikleri_saglayabilecek_node_IDs3to1,...          %ikincikontrol
                                ozellikleri_saglayabilecek_node_IDs1to2,...   %ilk kontrol
                                ozellikleri_saglayabilecek_node_IDs2to2,...          %son kontrol
                                ozellikleri_saglayabilecek_node_IDs3to2,...
                                ozellikleri_saglayabilecek_node_IDs1to3,...   %ilk kontrol
                                ozellikleri_saglayabilecek_node_IDs2to3,...          %son kontrol
                                ozellikleri_saglayabilecek_node_IDs3to3,...
                                ActiveNodesAtStart,grno_a,grno_b,grno_c,av1,av2,av3);
            %matrisinde ilk yerlestirmeler ve passive'lerden bunlara gecenler yer aliyor.
        
     %check ow b a c
       if (coverageafteropt(2)<av2)
           
        [ ~,...
          ~,...
          ~,...
          ~,...
          ~,...
          ~,...
          ~,...
          ~,...
          Allplaced_afteropt] = usednodes_overwrite(allpossible_node_IDs2to2,grno_b,...    %highest cov
                                allpossible_node_IDs1to2,grno_a,...
                                allpossible_node_IDs3to2,grno_c,...                 %lowesr cov
                                Allplaced_afteropt,av2,av1,av3);

%check mincov a,b,c
        [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs1to1,grno_a,...    %highest cov
                        allpossible_node_IDs2to1,grno_b,...
                        allpossible_node_IDs3to1,grno_c,...                 
                                Allplaced_afteropt,av1,av2,av3);

        %check mincov c,a,b

        [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs3to3,grno_c,...    
                                allpossible_node_IDs1to3,grno_a,...
                                allpossible_node_IDs2to3,grno_b,...                 
                                Allplaced_afteropt,av3,av1,av2);
        
         [coverageafteropt] =findcoverage(Allplaced_afteropt,node_number,grno_a,grno_b,grno_c);
        end
    
 

       if (coverageafteropt(3)<av3)
           
       %check ow    
       [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt] = usednodes_overwrite(allpossible_node_IDs3to3,grno_c,...    %highest cov
                        allpossible_node_IDs1to3,grno_a,...
                        allpossible_node_IDs2to3,grno_b,...                 %lowesr cov
                        Allplaced_afteropt,av3,av1,av2);
       %check mincov a,b,c
       [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs1to1,grno_a,...    %highest cov
                        allpossible_node_IDs2to1,grno_b,...
                        allpossible_node_IDs3to1,grno_c,...                 
                                Allplaced_afteropt,av1,av2,av3);

        %check mincov b,a,c
        [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs2to2,grno_b,...    
                                allpossible_node_IDs1to2,grno_a,...
                                allpossible_node_IDs3to2,grno_c,...                 
                                Allplaced_afteropt,av2,av1,av3);


        [coverageafteropt] =findcoverage(Allplaced_afteropt,node_number,grno_a,grno_b,grno_c);

        
       end

       if (coverageafteropt(1)<av1)
%check ow a b c
        [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt] = usednodes_overwrite(allpossible_node_IDs1to1,grno_a,...    %highest cov
                        allpossible_node_IDs2to1,grno_b,...
                        allpossible_node_IDs3to1,grno_c,...                 %lowesr cov
                        Allplaced_afteropt,av1,av2,av3);
%check mincov b,a,c
        [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs2to2,grno_b,...    
                                allpossible_node_IDs1to2,grno_a,...
                                allpossible_node_IDs3to2,grno_c,...                 
                                Allplaced_afteropt,av2,av1,av3);
%check mincov a,b,c
        [ ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            ~,...
            Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs3to3,grno_c,...    
                                allpossible_node_IDs1to3,grno_a,...
                                allpossible_node_IDs2to3,grno_b,...                 
                                Allplaced_afteropt,av3,av1,av2);        

        [coverageafteropt] =findcoverage(Allplaced_afteropt,node_number,grno_a,grno_b,grno_c);
        
       end

    % katman



       
          [changedmatrix2,ConsumedEnergies,ConsumedEnergies_DPR,ConsumedEnergies_ENC]=...
             neo_finalized(Allplaced_afteropt,...
             energy_to_be_consumedALL,...
             nodes_overhead_energy_consumption_CI_ALL,...
             encryption_energy_ALL,target_CI1,target_CI2,target_CI3);
          aradeger=changedmatrix2;
        else
              [changedmatrix2,ConsumedEnergies,ConsumedEnergies_DPR,ConsumedEnergies_ENC]=...
             neo_finalized(ActiveNodesAtStart,...
             energy_to_be_consumedALL,...
             nodes_overhead_energy_consumption_CI_ALL,...
             encryption_energy_ALL,target_CI1,target_CI2,target_CI3);
                
                coverage_before_opt=initcoverages;
                coverageafteropt = initcoverages;  % Eğer koşul sağlanmazsa, başlangıç kaplamasını kullan
    
    end

% resulttable1(i,:)=neo_generatetables(i,node_number,coverage_before_opt,ActiveNodesAtStart,encryption_energy_ALL,OverheadMatrix192256128);
% resulttable2(i,:)=neo_generatetables(i,node_number,coverageaftermincovto1,Allplaced_afterMincov1,encryption_energy_ALL,OverheadMatrix192256128);
incov=coverage_before_opt*100;
% outcov=coverageaftermincovto1*100;
outcov=coverageafteropt*100
% testcov=coverageaftermincovto1a*100;

% outcov=coverageafterowriteto1*100;
init_cov_mat(row_ind,:)=incov;
outp_cov_mat(row_ind,:)=outcov;

% test_cov_mat(row_ind,:)=testcov;
row_ind = row_ind + 1;
disp(i);
end


B_column1 = outp_cov_mat(:, 1);
B_column2 = outp_cov_mat(:, 2);
B_column3 = outp_cov_mat(:, 3);


% X ekseni olarak satır numaralarını oluşturmak
x = 1:size(outp_cov_mat, 1);

figure(777);
clf;
hold on
title('OPTIMISATION');
set(gca, 'ylim', [0 100]);
set(gca, 'xlim', [0 B/M]);
xticks(0:500:5000); % X ekseninde 500'de bir kılavuz çizgileri (0, 500, 1000, ... 5000)
yticks(0:25:100);
xlabel('Round number');
ylabel('Network coverage percentage');
plot(x, B_column1, 'r','LineWidth', 1, 'DisplayName', 'Coverage of group 1 (AES-192)');
plot(x, B_column2, 'b', 'LineWidth', 1,'DisplayName', 'Coverage of group 2 (AES-256)');
plot(x, B_column3, 'k', 'LineWidth', 1,'DisplayName', 'Coverage of group 3 (AES-128)');
legend
grid on
hold off;


% C_column1 = test_cov_mat(:, 1);
% C_column2 = test_cov_mat(:, 2);
% C_column3 = test_cov_mat(:, 3);
% 
% 
% % X ekseni olarak satır numaralarını oluşturmak
% x1 = 1:size(test_cov_mat, 1);
% 
% figure(3);
% hold on
% title('WITH OPTIMISATION');
% set(gca, 'ylim', [0 100]);
% set(gca, 'xlim', [0 B/M]);
% plot(x1, C_column1, 'r','LineWidth', 1, 'DisplayName', 'coverage of group 1 (AES-192)');
% plot(x1, C_column2, 'b', 'LineWidth', 1,'DisplayName', 'coverage of group 2 (AES-256)');
% plot(x1, C_column3, 'k', 'LineWidth', 1,'DisplayName', 'coverage of group 3 (AES-128)');
% legend
% hold off;

% %% original 
% %tektek
% clear
% clc
% sim_INPUTS;
% 
% [grno_a,grno_b,grno_c,generate_CI1,generate_CI2,generate_CI3,...
%     node_group1,node_group2,node_group3,target_CIA_in_av_order]=...
%     neoGenerateNodesFunction(node_number,israndom,budget,potentialimpact_n1,potentialimpact_n2,potentialimpact_n3);     %test icin icerde deger ver
% 
% 
% %create ALLNODES for decision input
% placezero=zeros(node_number,1);
% ALLNODES=[node_group1,placezero,node_group2,placezero,node_group3,placezero];
% NodesAtStart=ALLNODES;
% changedmatrix2=ALLNODES;
% 
% boy=size(1:M:B ,2);
% init_cov_mat=zeros(boy,3);
% passive_cov_mat=zeros(boy,3);
% outp_cov_mat=zeros(boy,3);
% 
% row_ind=1;
% %FOR LOOP BURAYA GELECEK
% for i=1:M:B
%     ALLNODES=changedmatrix2;
%     places=[6, 12, 18];
%     ALLNODES(:,places)=0;
%         node_group1p=ALLNODES(:,1:5);
%         node_group2p=ALLNODES(:,7:11);
%         node_group3p=ALLNODES(:,13:17);
% 
%     [av1,av2,av3,target_CI1,target_CI2,target_CI3,...
%         node_CI1, node_CI2,node_CI3 ,energy_to_be_consumedALL,...
%         nodes_overhead_energy_consumption_CI_ALL,encryption_energy_ALL,OverheadMatrix128192256]=...
%         neoCalculateNeededEnergiesFunction(total_blocks,target_CIA_in_av_order,...
%                                             generate_CI1,generate_CI2,generate_CI3,...
%                                             node_group1p,node_group2p,node_group3p);
%     energyisimleriatama
% 
%     %ALLNODES
%     % tic
%     neo_findallpossiblenodes   %%findallpossiblenodes1 dersen sadece 1incileri bulur
%     % disp('find node complete');
% 
%     [used_node_specs1,used_node_specs2,used_node_specs3,...
%                 ActiveNodesAtStart,initcoverages]=...
%                 neo_InitialActiveNodes( ozellikleri_saglayan_nodelarin_spec1to1,...
%                                         ozellikleri_saglayan_nodelarin_spec3to1,...
%                                         ozellikleri_saglayan_nodelarin_spec2to1,...
%                                         ozellikleri_saglayan_nodelarin_spec2to2,...
%                                         ozellikleri_saglayan_nodelarin_spec3to2,...
%                                         ozellikleri_saglayan_nodelarin_spec1to2,...
%                                         ozellikleri_saglayan_nodelarin_spec3to3,...
%                                         ozellikleri_saglayan_nodelarin_spec2to3,...
%                                         ozellikleri_saglayan_nodelarin_spec1to3,...
%                                         ALLNODES,grno_a,grno_b,grno_c);
%     %ActiveNodesAtStart   %ilk yerlestirmeler sadece her grupta yer alan active nodeları buluyor
%     %bunu optimizasyon adımı olarak kullanmadim optimizasyon oncesini gormek
%     %icin kullandim ve calistirdim  matrisi optimizasyonsuz degerleri verir
%     % initcoverages;
% 
%     if (initcoverages(1) < av1 || initcoverages(2) < av2 || initcoverages(3) < av3) 
% 
% 
%         [Allplaced_afteropt,coverageafteropt,...                      %ALLplacednodes_w_passives ,coverage after passive
%             used_passive_node_specs1,used_passive_node_specs2,used_passive_node_specs3]=...
%             neo_CheckPassiveNodesfunc(ozellikleri_saglayabilecek_node_IDs1to1,...   %ilk kontrol
%                                 ozellikleri_saglayabilecek_node_IDs2to1,...          %son kontrol
%                                 ozellikleri_saglayabilecek_node_IDs3to1,...          %ikincikontrol
%                                 ozellikleri_saglayabilecek_node_IDs1to2,...   %ilk kontrol
%                                 ozellikleri_saglayabilecek_node_IDs2to2,...          %son kontrol
%                                 ozellikleri_saglayabilecek_node_IDs3to2,...
%                                 ozellikleri_saglayabilecek_node_IDs1to3,...   %ilk kontrol
%                                 ozellikleri_saglayabilecek_node_IDs2to3,...          %son kontrol
%                                 ozellikleri_saglayabilecek_node_IDs3to3,...
%                                 ActiveNodesAtStart,grno_a,grno_b,grno_c,av1,av2,av3);
%             %matrisinde ilk yerlestirmeler ve passive'lerden bunlara gecenler yer aliyor.
% 
% 
%        if (coverageafteropt(2)<av2)
% 
%         [ ~,...
%           ~,...
%           ~,...
%           ~,...
%           ~,...
%           ~,...
%           ~,...
%           ~,...
%           Allplaced_afteropt] = usednodes_overwrite(allpossible_node_IDs2to2,grno_b,...    %highest cov
%                                 allpossible_node_IDs1to2,grno_a,...
%                                 allpossible_node_IDs3to2,grno_c,...                 %lowesr cov
%                                 Allplaced_afteropt,av2,av1,av3);
% 
% 
%         [ ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs1to1,grno_a,...    %highest cov
%                         allpossible_node_IDs2to1,grno_b,...
%                         allpossible_node_IDs3to1,grno_c,...                 
%                                 Allplaced_afteropt,av1,av2,av3);
% 
%                 [ ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs3to3,grno_c,...    
%                                 allpossible_node_IDs1to3,grno_a,...
%                                 allpossible_node_IDs2to2,grno_b,...                 
%                                 Allplaced_afteropt,av3,av1,av2);
% 
%          [coverageafteropt] =findcoverage(Allplaced_afteropt,node_number,grno_a,grno_b,grno_c);
%         end
% 
% 
% 
%        if (coverageafteropt(3)<av3)
% 
% 
%            [ ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   Allplaced_afteropt] = usednodes_overwrite(allpossible_node_IDs3to3,grno_c,...    %highest cov
%                         allpossible_node_IDs1to3,grno_a,...
%                         allpossible_node_IDs2to3,grno_b,...                 %lowesr cov
%                         Allplaced_afteropt,av3,av1,av2);
%         [ ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs1to1,grno_a,...    %highest cov
%                         allpossible_node_IDs2to1,grno_b,...
%                         allpossible_node_IDs3to1,grno_c,...                 
%                                 Allplaced_afteropt,av1,av2,av3);
% 
% 
%         [ ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs2to2,grno_b,...    
%                                 allpossible_node_IDs1to2,grno_a,...
%                                 allpossible_node_IDs3to2,grno_c,...                 
%                                 Allplaced_afteropt,av2,av1,av3);
% 
% 
%         [coverageafteropt] =findcoverage(Allplaced_afteropt,node_number,grno_a,grno_b,grno_c);
% 
% 
%        end
% 
%        if (coverageafteropt(1)<av1)
% 
%                       [ ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   ~,...
%   Allplaced_afteropt] = usednodes_overwrite(allpossible_node_IDs1to1,grno_a,...    %highest cov
%                         allpossible_node_IDs2to1,grno_b,...
%                         allpossible_node_IDs3to1,grno_c,...                 %lowesr cov
%                         Allplaced_afteropt,av1,av2,av3);
% 
%         [ ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs2to2,grno_b,...    
%                                 allpossible_node_IDs1to2,grno_a,...
%                                 allpossible_node_IDs3to2,grno_c,...                 
%                                 Allplaced_afteropt,av2,av1,av3);
% 
%         [ ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             ~,...
%             Allplaced_afteropt,~] = usednodes_mincov(allpossible_node_IDs2to2,grno_b,...    
%                                 allpossible_node_IDs1to2,grno_a,...
%                                 allpossible_node_IDs3to2,grno_c,...                 
%                                 Allplaced_afteropt,av2,av1,av3);        
% 
%         [coverageafteropt] =findcoverage(Allplaced_afteropt,node_number,grno_a,grno_b,grno_c);
% 
%        end
% 
%     katman
% 
% 
% 
% 
%           [changedmatrix2,ConsumedEnergies,ConsumedEnergies_DPR,ConsumedEnergies_ENC]=...
%              neo_finalized(Allplaced_afteropt,...
%              energy_to_be_consumedALL,...
%              nodes_overhead_energy_consumption_CI_ALL,...
%              encryption_energy_ALL,target_CI1,target_CI2,target_CI3);
%           aradeger=changedmatrix2;
%         else
%               [changedmatrix2,ConsumedEnergies,ConsumedEnergies_DPR,ConsumedEnergies_ENC]=...
%              neo_finalized(ActiveNodesAtStart,...
%              energy_to_be_consumedALL,...
%              nodes_overhead_energy_consumption_CI_ALL,...
%              encryption_energy_ALL,target_CI1,target_CI2,target_CI3);
% 
%                 coverage_before_opt=initcoverages;
%                 coverageafteropt = initcoverages;  % Eğer koşul sağlanmazsa, başlangıç kaplamasını kullan
% 
%     end
% 
% % resulttable1(i,:)=neo_generatetables(i,node_number,coverage_before_opt,ActiveNodesAtStart,encryption_energy_ALL,OverheadMatrix192256128);
% % resulttable2(i,:)=neo_generatetables(i,node_number,coverageaftermincovto1,Allplaced_afterMincov1,encryption_energy_ALL,OverheadMatrix192256128);
% incov=coverage_before_opt*100;
% % outcov=coverageaftermincovto1*100;
% outcov=coverageafteropt*100
% % testcov=coverageaftermincovto1a*100;
% 
% % outcov=coverageafterowriteto1*100;
% init_cov_mat(row_ind,:)=incov;
% outp_cov_mat(row_ind,:)=outcov;
% 
% % test_cov_mat(row_ind,:)=testcov;
% row_ind = row_ind + 1;
% disp(i);
% end
% 
% 
% B_column1 = outp_cov_mat(:, 1);
% B_column2 = outp_cov_mat(:, 2);
% B_column3 = outp_cov_mat(:, 3);
% 
% 
% % X ekseni olarak satır numaralarını oluşturmak
% x = 1:size(outp_cov_mat, 1);
% 
% figure(777);
% clf;
% hold on
% title('OPTIMISATION');
% set(gca, 'ylim', [0 110]);
% set(gca, 'xlim', [0 B/M]);
% plot(x, B_column1, 'r','LineWidth', 1, 'DisplayName', 'coverage of group 1 (AES-192)');
% plot(x, B_column2, 'b', 'LineWidth', 1,'DisplayName', 'coverage of group 2 (AES-256)');
% plot(x, B_column3, 'k', 'LineWidth', 1,'DisplayName', 'coverage of group 3 (AES-128)');
% legend
% hold off;
% 
% 
% % C_column1 = test_cov_mat(:, 1);
% % C_column2 = test_cov_mat(:, 2);
% % C_column3 = test_cov_mat(:, 3);
% % 
% % 
% % % X ekseni olarak satır numaralarını oluşturmak
% % x1 = 1:size(test_cov_mat, 1);
% % 
% % figure(3);
% % hold on
% % title('WITH OPTIMISATION');
% % set(gca, 'ylim', [0 100]);
% % set(gca, 'xlim', [0 B/M]);
% % plot(x1, C_column1, 'r','LineWidth', 1, 'DisplayName', 'coverage of group 1 (AES-192)');
% % plot(x1, C_column2, 'b', 'LineWidth', 1,'DisplayName', 'coverage of group 2 (AES-256)');
% % plot(x1, C_column3, 'k', 'LineWidth', 1,'DisplayName', 'coverage of group 3 (AES-128)');
% % legend
% hold off;

