function [Allplaced_afterMincov1,coverageaftermincovto1, coverageaftermincovto2, coverageaftermincovto3]=...
    neo_CheckMinCov(ALLplacednodes_w_passives,...
    allpossible_node_IDs3to3, ...
    allpossible_node_IDs1to3, ...
    allpossible_node_IDs2to3,...
    allpossible_node_IDs3to2, ...
    allpossible_node_IDs1to2, ...
    allpossible_node_IDs2to2,...
    allpossible_node_IDs3to1, ...
    allpossible_node_IDs1to1, ...
    allpossible_node_IDs2to1,...
    grno_a,grno_b,grno_c,av1,av2,av3)

node_number=size(ALLplacednodes_w_passives,1);
av_a=av1;
av_b=av2;
av_c=av3;

%ucuncuye optimize
[ used_mincov_node_IDs3,...
  used_mincov_node_GRs3,...
  used_mincov_node_specs3,...
  other_mincov_ID13,...
  other_mincov_ID23,...
  additionlly_mincov_accepted_node_IDs3,...
  additionlly_mincov_accepted_node_GRs3,...
  additionlly_mincov_accepted_node_specs3,...
  Allplaced_afterMincov3] = usednodes_mincov(allpossible_node_IDs3to3,grno_c,...    
                        allpossible_node_IDs1to3,grno_a,...
                        allpossible_node_IDs2to3,grno_b,...                 
                        ALLplacednodes_w_passives,av_c,av_a,av_b);



%ikinciye optimize
[ used_mincov_node_IDs2,...
  used_mincov_node_GRs2,...
  used_mincov_node_specs2,...
  other_mincov_ID12,...
  other_mincov_ID32,...
  additionlly_mincov_accepted_node_IDs12,...
  additionlly_mincov_accepted_node_GRs12,...
  additionlly_mincov_accepted_node_specs2,...
  Allplaced_afterMincov2] = usednodes_mincov(allpossible_node_IDs2to2,grno_b,...    
                        allpossible_node_IDs1to2,grno_a,...
                        allpossible_node_IDs3to2,grno_c,...                 
                        Allplaced_afterMincov3,av_b,av_a,av_c);

%birinciye optimize
[ used_mincov_node_IDs1,...
  used_mincov_node_GRs1,...
  used_mincov_node_specs1,...
  other_mincov_ID2,...
  other_mincov_ID3,...
  additionlly_accepted_mincov_node_IDs1,...
  additionlly_accepted_mincov_node_GRs1,...
  additionlly_accepted_mincov_node_specs,...
  Allplaced_afterMincov1] = usednodes_mincov(allpossible_node_IDs1to1,grno_a,...    %highest cov
                        allpossible_node_IDs2to1,grno_b,...
                        allpossible_node_IDs3to1,grno_c,...                 %lowesr cov
                        Allplaced_afterMincov2,av_a,av_b,av_c);





%ilk yerlestirmeden sonra place coverage guncelleme
coverage1aftermincovto3= calculatecoverage_no_consumtpion(Allplaced_afterMincov3,grno_a,node_number);
coverage2aftermincovto3= calculatecoverage_no_consumtpion(Allplaced_afterMincov3,grno_b,node_number);
coverage3aftermincovto3= calculatecoverage_no_consumtpion(Allplaced_afterMincov3,grno_c,node_number);

% yerlestirmeden sonra placed coverage guncelleme
coverage1aftermincovto2= calculatecoverage_no_consumtpion(Allplaced_afterMincov2,grno_a,node_number);
coverage2aftermincovto2= calculatecoverage_no_consumtpion(Allplaced_afterMincov2,grno_b,node_number);
coverage3aftermincovto2= calculatecoverage_no_consumtpion(Allplaced_afterMincov2,grno_c,node_number);


% yerlestirmeden sonra placed coverage guncelleme
coverage1aftermincovto1= calculatecoverage_no_consumtpion(Allplaced_afterMincov1,grno_a,node_number);
coverage2aftermincovto1= calculatecoverage_no_consumtpion(Allplaced_afterMincov1,grno_b,node_number);
coverage3aftermincovto1= calculatecoverage_no_consumtpion(Allplaced_afterMincov1,grno_c,node_number);

%covereagelar
% initcoverages
% coverageafterpassives
coverageaftermincovto3=[coverage1aftermincovto3,coverage2aftermincovto3,coverage3aftermincovto3];
coverageaftermincovto2=[coverage1aftermincovto2,coverage2aftermincovto2,coverage3aftermincovto2];
coverageaftermincovto1=[coverage1aftermincovto1,coverage2aftermincovto1,coverage3aftermincovto1];
% end